WITH COMPANY_PERIOD_TYPE AS (
    SELECT COMPANY_ID, MODE(PERIOD_TYPE) AS FREQ_PERIOD_TYPE
    FROM FACT_CONTRIBUTIONS
    WHERE CONTRIBUTION_STATE IN (
     'released',
     'created',
     'payment_pending',
     'investing',
     'invested',
     'paid')
    GROUP BY COMPANY_ID
)
SELECT
       FC.COMPANY_ID
      , FC.COMPANY_SIZE_BAND
      , REG_ADDRESS_DISTRICT
      , REG_ADDRESS_REGION
      , SIC2007_CATEGORY
      , LEGAL_STRUCTURE
      , FC.STATE
      , datediff(year,DATE_OF_CREATION, IFNULL(DATE_OF_CESSATION, GETDATE())) AS COMPANY_AGE
      , CH.REGADDRESS_POSTTOWN
      , CPT.FREQ_PERIOD_TYPE

FROM FACT_COMPANIES FC
    JOIN COMPANY_PERIOD_TYPE CPT ON FC.COMPANY_ID = CPT.COMPANY_ID
    LEFT JOIN COMPANIES_HOUSE2 CH2 ON FC.COMPANY_ID = CH2.COMPANY_ID
    LEFT JOIN COMPANIES_HOUSE CH ON CH.COMPANYNUMBER = CH2.COMPANY_NUMBER
WHERE FC.REGISTRATION_NUMBER not ILIKE ('%sptest%');



