WITH MONTHLY_CONTRIBUTION AS
(WITH DT_QUARTERLY AS (
    WITH Q AS (
        SELECT CONTRIBUTION_ID
             , ENDS_ON                       AS ENDS_ON_1
             , DATEADD('month', -1, ENDS_ON) as ENDS_ON_2
             , DATEADD('month', -2, ENDS_ON) as ENDS_ON_3
        FROM FACT_CONTRIBUTIONS FC
        WHERE 1 = 1
          AND PERIOD_TYPE IN ('Quarterly')
          AND IS_REFUNDED = FALSE
          AND PAYMENT_HAS_ISSUE = FALSE
        ORDER BY CONTRIBUTION_ID
    )
    select CONTRIBUTION_ID, YEAR(DT) AS DT_Y, MONTH(DT) AS DT_M
    from Q
        unpivot (DT for month in (ENDS_ON_1, ENDS_ON_2, ENDS_ON_3))
    order by CONTRIBUTION_ID
),
DT_BIANNUALLY AS (
    WITH Q AS (
        SELECT CONTRIBUTION_ID
             , ENDS_ON                       AS ENDS_ON_1
             , DATEADD('month', -1, ENDS_ON) as ENDS_ON_2
             , DATEADD('month', -2, ENDS_ON) as ENDS_ON_3
             , DATEADD('month', -3, ENDS_ON) as ENDS_ON_4
             , DATEADD('month', -4, ENDS_ON) as ENDS_ON_5
             , DATEADD('month', -5, ENDS_ON) as ENDS_ON_6
        FROM FACT_CONTRIBUTIONS FC
        WHERE 1 = 1
          AND PERIOD_TYPE IN ('BiAnnually')
          AND IS_REFUNDED = FALSE
          AND PAYMENT_HAS_ISSUE = FALSE
        ORDER BY CONTRIBUTION_ID
    )
    select CONTRIBUTION_ID, YEAR(DT) AS DT_Y, MONTH(DT) AS DT_M
    from Q
        unpivot (DT for month in (ENDS_ON_1, ENDS_ON_2, ENDS_ON_3, ENDS_ON_4, ENDS_ON_5, ENDS_ON_6))
    order by CONTRIBUTION_ID, DT_Y, DT_M
),
DT_ANNUALLY AS (
    WITH Q AS (
        SELECT CONTRIBUTION_ID
             , ENDS_ON                       AS ENDS_ON_1
             , DATEADD('month', -1, ENDS_ON) as ENDS_ON_2
             , DATEADD('month', -2, ENDS_ON) as ENDS_ON_3
             , DATEADD('month', -3, ENDS_ON) as ENDS_ON_4
             , DATEADD('month', -4, ENDS_ON) as ENDS_ON_5
             , DATEADD('month', -5, ENDS_ON) as ENDS_ON_6
             , DATEADD('month', -6, ENDS_ON) as ENDS_ON_7
             , DATEADD('month', -7, ENDS_ON) as ENDS_ON_8
             , DATEADD('month', -8, ENDS_ON) as ENDS_ON_9
             , DATEADD('month', -9, ENDS_ON) as ENDS_ON_10
             , DATEADD('month', -10, ENDS_ON) as ENDS_ON_11
             , DATEADD('month', -11, ENDS_ON) as ENDS_ON_12
        FROM FACT_CONTRIBUTIONS FC
        WHERE 1 = 1
          AND PERIOD_TYPE IN ('Annually')
          AND IS_REFUNDED = FALSE
          AND PAYMENT_HAS_ISSUE = FALSE
        ORDER BY CONTRIBUTION_ID
    )
    select CONTRIBUTION_ID, YEAR(DT) AS DT_Y, MONTH(DT) AS DT_M
    from Q
        unpivot (DT for month in (ENDS_ON_1, ENDS_ON_2, ENDS_ON_3, ENDS_ON_4, ENDS_ON_5, ENDS_ON_6,
            ENDS_ON_7, ENDS_ON_8, ENDS_ON_9, ENDS_ON_10, ENDS_ON_11, ENDS_ON_12))
    order by CONTRIBUTION_ID, DT_Y, DT_M
)
SELECT
     FC.EMPLOYEE_ID
     , YEAR(FC.ENDS_ON) Y
     , MONTH(FC.ENDS_ON) M
     , SUM(TOTAL_AMOUNT_PENNIES) AS TOTAL_AMOUNT_PENNIES
     , AVG(FC.EMPLOYEE_PERCENTAGE) AS EMPLOYEE_PERCENTAGE
     , AVG(FC.COMPANY_PERCENTAGE) AS COMPANY_PERCENTAGE
     , AVG(PENSIONABLE_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(PERIOD_TYPE)/12) AS PENSIONABLE_EARNINGS_PENNIES
     , AVG(GROSS_QUALIFYING_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(PERIOD_TYPE)/12) AS GROSS_QUALIFYING_EARNINGS_PENNIES
FROM FACT_CONTRIBUTIONS FC
WHERE 1 = 1
AND PERIOD_TYPE IN ('Weekly','FourWeekly','Fortnightly')
AND IS_REFUNDED = FALSE
AND PAYMENT_HAS_ISSUE = FALSE
AND CONTRIBUTION_STATE IN (
     'released',
     'created',
     'payment_pending',
     'investing',
     'invested',
     'paid')
GROUP BY FC.EMPLOYEE_ID, YEAR(FC.ENDS_ON), MONTH(FC.ENDS_ON)

UNION

SELECT
       FC.EMPLOYEE_ID
     , YEAR(FC.ENDS_ON) AS Y
     , MONTH(FC.ENDS_ON) AS M
     , FC.TOTAL_AMOUNT_PENNIES/(12/PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE)) as TOTAL_AMOUNT_PENNIES
     , FC.EMPLOYEE_PERCENTAGE
     , FC.COMPANY_PERCENTAGE
     , FC.PENSIONABLE_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE) / 12
     , FC.GROSS_QUALIFYING_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE) / 12
FROM FACT_CONTRIBUTIONS FC
WHERE 1 = 1
AND CONTRIBUTION_STATE IN (
     'released',
     'created',
     'payment_pending',
     'investing',
     'invested',
     'paid')
AND PERIOD_TYPE IN ('Monthly')
AND IS_REFUNDED = FALSE
AND PAYMENT_HAS_ISSUE = FALSE

UNION

SELECT
       FC.EMPLOYEE_ID
     , DT_Y AS Y
     , DT_M AS M
     , FC.TOTAL_AMOUNT_PENNIES/(12/PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE)) as TOTAL_AMOUNT_PENNIES
     , FC.EMPLOYEE_PERCENTAGE
     , FC.COMPANY_PERCENTAGE
     , FC.PENSIONABLE_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE) / 12
     , FC.GROSS_QUALIFYING_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE) / 12
FROM FACT_CONTRIBUTIONS FC
JOIN DT_QUARTERLY ON DT_QUARTERLY.CONTRIBUTION_ID = FC.CONTRIBUTION_ID
WHERE 1 = 1
AND CONTRIBUTION_STATE IN (
     'released',
     'created',
     'payment_pending',
     'investing',
     'invested',
     'paid')
AND PERIOD_TYPE IN ('Quarterly')
AND IS_REFUNDED = FALSE
AND PAYMENT_HAS_ISSUE = FALSE

UNION

SELECT
       FC.EMPLOYEE_ID
     , DT_Y AS Y
     , DT_M AS M
     , FC.TOTAL_AMOUNT_PENNIES/(12/PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE)) as TOTAL_AMOUNT_PENNIES
     , FC.EMPLOYEE_PERCENTAGE
     , FC.COMPANY_PERCENTAGE
     , FC.PENSIONABLE_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE) / 12
     , FC.GROSS_QUALIFYING_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE) / 12
FROM FACT_CONTRIBUTIONS FC
JOIN DT_BIANNUALLY ON DT_BIANNUALLY.CONTRIBUTION_ID = FC.CONTRIBUTION_ID
WHERE 1 = 1
AND CONTRIBUTION_STATE IN (
     'released',
     'created',
     'payment_pending',
     'investing',
     'invested',
     'paid')
AND PERIOD_TYPE IN ('BiAnnually')
AND IS_REFUNDED = FALSE
AND PAYMENT_HAS_ISSUE = FALSE

UNION

SELECT
       FC.EMPLOYEE_ID
     , DT_Y AS Y
     , DT_M AS M
     , FC.TOTAL_AMOUNT_PENNIES/(12/PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE)) as TOTAL_AMOUNT_PENNIES
     , FC.EMPLOYEE_PERCENTAGE
     , FC.COMPANY_PERCENTAGE
     , FC.PENSIONABLE_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE) / 12
     , FC.GROSS_QUALIFYING_EARNINGS_PENNIES * PERIOD_TYPE_TO_NUMBER(FC.PERIOD_TYPE) / 12
FROM FACT_CONTRIBUTIONS FC
JOIN DT_ANNUALLY ON DT_ANNUALLY.CONTRIBUTION_ID = FC.CONTRIBUTION_ID
WHERE 1 = 1
AND CONTRIBUTION_STATE IN (
     'released',
     'created',
     'payment_pending',
     'investing',
     'invested',
     'paid')
AND PERIOD_TYPE IN ('Annually')
AND IS_REFUNDED = FALSE
AND PAYMENT_HAS_ISSUE = FALSE
    )
SELECT
       MC.EMPLOYEE_ID
     , FE.COMPANY_ID
     , FE.GENDER
     , FE.AGE
     , MC.Y
     , MC.M
     , CAST(ROUND(SUM(MC.TOTAL_AMOUNT_PENNIES)) AS INT) AS TOTAL_AMOUNT_PENNIES
     , AVG(MC.EMPLOYEE_PERCENTAGE) AS EMPLOYEE_PERCENTAGE
     , AVG(MC.COMPANY_PERCENTAGE) AS COMPANY_PERCENTAGE
     , CAST(ROUND(AVG(MC.PENSIONABLE_EARNINGS_PENNIES)) AS INT) AS PENSIONABLE_EARNINGS_PENNIES
     , CAST(ROUND(AVG(MC.GROSS_QUALIFYING_EARNINGS_PENNIES)) AS INT) AS GROSS_QUALIFYING_EARNINGS_PENNIES
FROM MONTHLY_CONTRIBUTION MC
JOIN FACT_EMPLOYEES FE ON MC.EMPLOYEE_ID = FE.EMPLOYEE_ID
INNER JOIN FACT_COMPANIES FC ON FE.COMPANY_ID = FC.COMPANY_ID
WHERE 1=1
AND FC.REGISTRATION_NUMBER not ilike 'sptest%' -- remove test data
AND FE.OPT_STATE != 'ignition'
GROUP BY MC.EMPLOYEE_ID, FE.COMPANY_ID, FE.GENDER, FE.AGE, MC.Y, MC.M
ORDER BY EMPLOYEE_ID, MC.Y, MC.M;
